name: update_manifesh

on:
  workflow_call:
    inputs:
      imagename:
        required: true
        type: string
jobs:
  update_tag:
    runs-on: self-hosted
    steps:
    - name: 🤘 checkout
      uses: actions/checkout@v3
      with:
        repository: 'tidlor-ins/argoCD'
        ref: 'master'
        token: ${{ secrets.my_pat }}
    - name: Set variable
      run: |-
        echo "BRANCH=$(echo $GITHUB_REF | cut -d'/' -f 3)" >> $GITHUB_ENV  
    - name: Is dev?
      if: env.BRANCH == 'dev' 
      run: echo "DIR=deploy/dev" >> $GITHUB_ENV;
    - name: Is develop?
      if: env.BRANCH == 'develop' 
      run: echo "DIR=deploy/dev" >> $GITHUB_ENV;
    - name: Is sit?
      if: env.BRANCH == 'sit'
      run: echo "DIR=deploy/sit" >> $GITHUB_ENV;
    - name: Is uat?
      if: env.BRANCH == 'uat'
      run: echo "DIR=deploy/uat" >> $GITHUB_ENV;
    - name: Is preprod?
      if: env.BRANCH == 'preprod'
      run: echo "DIR=deploy/pre" >> $GITHUB_ENV;
    - name: Is master?
      if: env.BRANCH == 'master'
      run: echo "DIR=deploy/production" >> $GITHUB_ENV;
    - name: Set up Kustomize
      uses: imranismail/setup-kustomize@v1
    - name: Set Tag
      run: | 
        echo "TAG=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV;
        echo ${{ inputs.imagename }};
    - name: Patch kustomize
      run: |-
        cd ${{ github.event.repository.name }}/${{ env.DIR }}
        echo "kustomize update ${{ env.DIR }}"
        kustomize edit set image insuranceitteam/${{ inputs.imagename }}
        cat kustomization.yml
        
    - name: Push update manifesh to ArgoCD repo
      run: |
        echo "REPO_NAME=${{ github.event.repository.name }}"
        ls
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "update manifesh"
        git push
