name: Reusable workflow example

on:
  workflow_call:
    inputs:
      imagename:
        required: true
        type: string
      buildtype:
        required: false
        default: docker
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true
      NPM_TOKEN:
        required: true
    outputs:
      imgname:
        value: ${{ jobs.build.outputs.output1 }}


jobs:
  build:
    runs-on: self-hosted
    outputs:
      output1: ${{ steps.step1.outputs.imgname }}
    steps:   
    - uses: actions/checkout@v3
    - name: Is master?
      if: github.ref == 'refs/heads/master'
      uses: codfish/semantic-release-action@v1
      with:
        branches: |
          [
            'master',
            'dev',
          ]
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      
    - name: Set Tag
      run: |
        echo $RELEASE_VERSION
        echo $RELEASE_MAJOR
        echo $RELEASE_MINOR
        echo $RELEASE_PATCH
        if $GITHUB_REF =='refs/heads/master' && $RELEASE_VERSION !='' ; then
        echo "TAG=$(echo v$RELEASE_VERSION | cut -c 1-7)" >> $GITHUB_ENV;
        else
        echo "TAG=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV;
        fi
    #   if: github.ref == 'refs/heads/master' && "${{ RELEASE_VERSION != '' }}"
    #   run: echo "TAG=$(echo v$RELEASE_VERSION | cut -c 1-7)" >> $GITHUB_ENV;
    # - if: github.ref != 'refs/heads/master'
    #   run: echo "TAG=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV;
    - id: step1
      run: echo "::set-output name=imgname::${{ inputs.imagename }}:${{ env.TAG }}"
    - name: Kaniko build
      uses: aevea/action-kaniko@master
      with:
        image: insuranceitteam/${{ inputs.imagename }}
        tag: ${{ env.TAG }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        cache: true
        cache_registry: insuranceitteam/${{ inputs.imagename }}



